name: Build Playnite Extensions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: './source'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Nuget Restore
        run: |
          nuget restore .\source\source\SuccessStory.sln

      - name: Build entire solution (with .NET Framework 4.6.2)
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\source\source\SuccessStory.sln -p:Configuration=Release -restore

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuccessStory
          path: |
            .\source\source\bin\Release\*
